Test issue creation / label comment automation
arXiv/html_feedback pull request #124
Opened 2023-11-10 01:24 UTC by crazy-bai

Whenever an issue is created or a label is marked, the comment will automatically generated.

2023-11-13 18:52 UTC, alisonhofer commented on .github/workflows/comment_automation.yml
> +            const issueComment = `Hello @${{ github.actor }}, thanks for the issue report! Your report is being reviewed and will be addressed as soon as possible.`;
`Hello @${{ github.actor }}, thanks for the issue report! We are reviewing your report and will address it as soon as possible.

2023-11-17 15:20 UTC, crazy-bai reviewed
I will change the automated  issue comment to what you comment below.

2023-11-17 20:56 UTC, chrisjcameron requested changes
Don't overwrite repo readme

2023-11-17 20:58 UTC, chrisjcameron commented on .github/workflows/comment_automation.yml
Are the backticks the correct quotation mark around the issueComment? I don't see any similar examples in YAML.

2023-12-01 16:22 UTC, chrisjcameron approved these changes

2023-12-01 16:23 UTC, merged